version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres_db
      - redis
    networks:
      - authors-heaven
  
  postgres_db:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    networks:
      - authors-heaven 

  redis:
    image: redis:6-alpine
    entrypoint: redis-server --appendonly no --save ""
    ports:
      - 6379:6379
    networks:
      - authors-heaven

  worker:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /worker
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    env_file:
      - .env
    depends_on:
      - redis
      - api
    networks:
      - authors-heaven

networks:
  authors-heaven:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume: